[tool.poetry]
name = "cosem-flows"
version = "0.1.0"
description = "Workflows for COSEM"
authors = ["Davis Vann Bennett <davis.v.bennett@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
xarray-multiscale = "^0.1.0"
fibsem-tools = "^0.1.0"
sheetscrape = "^0.1.0"
pymongo = "^3.11.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
